name: Build workshop

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v5

      - name: Get postgres version
        run: |
          sudo service postgresql start
          pgver=$(psql --version | grep -Po '(?<=psql \(PostgreSQL\) )[^;]+(?=\.\d+ \()')
          echo "PGVER=${pgver}" >> $GITHUB_ENV
          echo "PGIS=3" >> $GITHUB_ENV

      - name: Add PostgreSQL APT repository
        run: |
          sudo apt-get install curl ca-certificates gnupg
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ \
            $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y osm2pgrouting \
            postgresql-${PGVER}-postgis-${PGIS} \
            postgresql-${PGVER}-postgis-${PGIS}-scripts \
            postgresql-${PGVER}-pgrouting

          python -m pip install --upgrade pip
          pip install -r REQUIREMENTS.txt
          pip list

      - name: Configure
        run: |
          service postgresql status
          sudo service postgresql start
          echo "here 1"
          service postgresql status
          sudo -u postgres createdb -p ${POSTGRES_PORT}  setup
          sudo -u postgres psql -c 'CREATE ROLE "runner" SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN PASSWORD $$runner$$;' -d setup
          echo :5432:*:runner:runner >> .pgpass
          sudo -u postgres psql -c 'CREATE ROLE "user" SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN PASSWORD $$user$$;' -d setup
          echo :5432:*:user:user >> .pgpass
          echo "here 5"
          mkdir -p  ~/Desktop/workshop-2019
          mkdir build
          cd build
          cmake -DPGR_WORKSHOP_DEBUG=ON -DES=ON -DSV=ON ..
          psql -l
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: setup

      - name: Build
        run: |
          cd build
          make html
